const COMPRESSED_VARIABLE_TYPES = [
  {
    type: "ActorId",
    list: [
      "actor_id",
      "player_id",
      "bot_id",
      "emoter_id",
      "player_1_id",
      "player_2_id",
    ],
  },
  {
    type: "ActorId[]",
    list: ["player_ids"],
  },
  { type: "SpriteId", list: ["sprite_id"] },
  { type: "TiledObjectOptions", list: ["object_options"] },
  { type: "TiledObjectData", list: ["object_data"] },
  { type: "BotOptions", list: ["bot_options"] },
  { type: "ActorKeyframe[]", list: ["keyframes"] },
  { type: "ItemDefinition", list: ["item_definition"] },
  { type: "TextboxOptions", list: ["textbox_options"] },
  { type: "SpriteOptions", list: ["sprite_options"] },
  { type: "ShopItem[]", list: ["shop_items"] },
  { type: "ShopItem", list: ["shop_item"] },
  { type: "BoardPost", list: ["posts"] },
  { type: "RequestOptions", list: ["request_options"] },
  { type: "Color", list: ["color"] },
  { type: "Promise<any>", list: ["promise"] },
  { type: "Promise<any>[]", list: ["promises"] },
  { type: "fun(value: T)", list: ["resolve"] },
  { type: "fun(): Promise<any>", list: ["async_iterator"] },
  { type: "number|string", list: ["object_id"] },
  {
    type: "boolean",
    list: [
      "bool",
      "warp",
      "warp_in",
      "warp_out",
      "flip_h",
      "flip_v",
      "rotate",
      "visibility",
      "loop",
      "solid",
      "open_instantly",
    ],
  },
  {
    type: "number",
    list: [
      "index",
      "layer",
      "x",
      "y",
      "z",
      "r",
      "g",
      "b",
      "a",
      "rotation",
      "width",
      "height",
      "tile_gid",
      "health",
      "money",
      "amount",
      "vel_x",
      "vel_y",
      "parallax",
      "range_x",
      "range_y",
      "seconds",
      "holdTimeInSeconds",
      "durationInSeconds",
      "strength",
      "character_limit",
    ],
  },
  {
    type: "string",
    list: [
      "text",
      "font_name",
      "emotion",
      "package_id",
      "direction",
      "area_id",
      "new_area_id",
      "tmx_string",
      "tileset_path",
      "address",
      "server_path",
      "item_id",
      "class",
      "type",
      "reason",
      "name",
      "path",
      "message",
      "texture_path",
      "animation_path",
      "mug_texture_path",
      "mug_animation_path",
      "emote_id",
      "state_name",
      "package_path",
      "code",
      "content",
      "option_a",
      "option_b",
      "option_c",
      "question",
      "name",
      "property_value",
      "board_name",
      "default_text",
      "data",
      "event_name",
      "url",
      "post_id",
    ],
  },
  { type: "string[]", list: ["Returns a list of area_ids"] },
  { type: "fun()", list: ["callback"] },
  { type: "any", list: ["encounter_data"] },
];

const VARIABLE_TYPE_MAP: { [name: string]: string } = {};

for (const { type, list } of COMPRESSED_VARIABLE_TYPES) {
  for (const name of list) {
    VARIABLE_TYPE_MAP[name] = type;
  }
}

export default function resolveVariableType(name: string): string | undefined {
  return VARIABLE_TYPE_MAP[name];
}
