import { DefinitionMap } from "../definition_map";

const FLAT_ENUMS = {
  Lifetime: ["Local", "Battle", "Scene"],
  Direction: [
    "None",
    "Up",
    "Left",
    "Down",
    "Right",
    "UpLeft",
    "UpRight",
    "DownLeft",
    "DownRight",
  ],
  Element: [
    "None",
    "Fire",
    "Aqua",
    "Elec",
    "Wood",
    "Sword",
    "Wind",
    "Cursor",
    "Summon",
    "Plus",
    "Break",
  ],
  Rank: [
    "V1",
    "V2",
    "V3",
    "V4",
    "V5",
    "SP",
    "EX",
    "Rare1",
    "Rare2",
    "NM",
    "RV",
    "DS",
    "Alpha",
    "Beta",
    "Omega",
    "Sigma",
  ],
  Highlight: ["None", "Flash", "Solid"],
  CardClass: ["Standard", "Mega", "Giga", "Dark"],
  Team: ["Other", "Red", "Blue"],
  AudioBehavior: ["Default", "NoOverlap"],
  Playback: ["Once", "Loop", "Bounce", "Reverse"],
  ColorMode: ["Additive", "Multiply"],
  Compare: ["LT", "LE", "EQ", "NE", "GT", "GE"],
  TileState: [
    "Hidden",
    "Normal",
    "PermaHole",
    "Cracked",
    "Broken",
    "Ice",
    "Grass",
    "Lava",
    "Poison",
    "Holy",
    "DirectionLeft",
    "DirectionRight",
    "DirectionUp",
    "DirectionDown",
    "Volcano",
    "Sea",
    "Sand",
    "Metal",
  ],
  DefensePriority: ["Barrier", "Body", "Action", "Trap", "Last"],
  DefenseOrder: ["Always", "CollisionOnly"],
};

const SPECIAL_ENUMS = {
  Hit: ["---@type { [string]: number }", "Hit = {}"],
  Input: [
    "---@enum Input",
    "Input = {",
    "  Held = {",
    "    Up = Input._,",
    "    Left = Input._,",
    "    Right = Input._,",
    "    Down = Input._,",
    "    Use = Input._,",
    "    Special = Input._,",
    "    Shoot = Input._,",
    "    FaceLeft = Input._,",
    "    FaceRight = Input._,",
    "    LeftShoulder = Input._,",
    "    RightShoulder = Input._,",
    "    EndTurn = Input._,",
    "    Ready = Input._,",
    "  },",
    "  Pressed = {",
    "    Up = Input._,",
    "    Left = Input._,",
    "    Right = Input._,",
    "    Down = Input._,",
    "    Use = Input._,",
    "    Special = Input._,",
    "    Shoot = Input._,",
    "    FaceLeft = Input._,",
    "    FaceRight = Input._,",
    "    LeftShoulder = Input._,",
    "    RightShoulder = Input._,",
    "    EndTurn = Input._,",
    "    Ready = Input._,",
    "  },",
    "}",
  ],
};

export function defineEnums(definitions: DefinitionMap) {
  for (const name in FLAT_ENUMS) {
    definitions[name] = [
      "---@enum " + name,
      name + " = {",
      ...FLAT_ENUMS[name].map((value_name) => `  ${value_name} = ${name}._,`),
      "}",
    ];
  }

  for (const name in SPECIAL_ENUMS) {
    definitions[name] = SPECIAL_ENUMS[name];
  }
}
