import { DefinitionMap } from "../../shared/definition_map";

const FLAT_ENUMS = {
  Shadow: ["None", "Small", "Big"],
  Lifetime: [
    "Local",
    "Battle",
    "Scene",
    "CardSelectOpen",
    "CardSelectClose",
    "Nil",
  ],
  Direction: [
    "None",
    "Up",
    "Left",
    "Down",
    "Right",
    "UpLeft",
    "UpRight",
    "DownLeft",
    "DownRight",
  ],
  Element: [
    "None",
    "Fire",
    "Aqua",
    "Elec",
    "Wood",
    "Sword",
    "Wind",
    "Cursor",
    "Summon",
    "Plus",
    "Break",
  ],
  Rank: [
    "V1",
    "V2",
    "V3",
    "V4",
    "V5",
    "SP",
    "EX",
    "Rare1",
    "Rare2",
    "NM",
    "RV",
    "DS",
    "Alpha",
    "Beta",
    "Omega",
    "Sigma",
  ],
  Highlight: ["None", "Flash", "Solid"],
  CardClass: ["Standard", "Mega", "Giga", "Dark"],
  Team: ["Other", "Red", "Blue"],
  AudioBehavior: ["Default", "NoOverlap"],
  Playback: ["Once", "Loop", "Bounce", "Reverse"],
  ColorMode: ["Additive", "Multiply"],
  SpriteShaderEffect: ["None", "Grayscale", "Pixelate"],
  Compare: ["LT", "LE", "EQ", "NE", "GT", "GE"],
  DefensePriority: ["Barrier", "Body", "Action", "Trap", "Last"],
  DefenseOrder: ["Always", "CollisionOnly"],
};

const SPECIAL_ENUMS = {
  Hit: [
    "---@enum Hit",
    "Hit = {",
    "  RetainIntangible = 0,",
    "  NoCounter = 0,",
    "  Drag = 0,",
    "  Impact = 0,",
    "  Flinch = 0,",
    "  Flash = 0,",
    "  Shake = 0,",
    "  PierceInvis = 0,",
    "  PierceGuard = 0,",
    "  PierceGround = 0,",
    "  Freeze = 0,",
    "  Paralyze = 0,",
    "  Root = 0,",
    "  Blind = 0,",
    "  Confuse = 0,",
    "}",
  ],
  TileState: [
    "---@type { [string]: {} }",
    "---@enum TileState",
    "TileState = {",
    "  Void = {},",
    "  Normal = {},",
    "  PermaHole = {},",
    "  Cracked = {},",
    "  Broken = {},",
    "}",
  ],
  Input: [
    "---@enum Input",
    "local _Input = { _ = {} }",
    "",
    "Input = {",
    "  Held = {",
    "    Up = _Input._,",
    "    Left = _Input._,",
    "    Right = _Input._,",
    "    Down = _Input._,",
    "    Use = _Input._,",
    "    Special = _Input._,",
    "    Shoot = _Input._,",
    "    FaceLeft = _Input._,",
    "    FaceRight = _Input._,",
    "    LeftShoulder = _Input._,",
    "    RightShoulder = _Input._,",
    "    EndTurn = _Input._,",
    "    Ready = _Input._,",
    "  },",
    "  Pressed = {",
    "    Up = _Input._,",
    "    Left = _Input._,",
    "    Right = _Input._,",
    "    Down = _Input._,",
    "    Use = _Input._,",
    "    Special = _Input._,",
    "    Shoot = _Input._,",
    "    FaceLeft = _Input._,",
    "    FaceRight = _Input._,",
    "    LeftShoulder = _Input._,",
    "    RightShoulder = _Input._,",
    "    EndTurn = _Input._,",
    "    Ready = _Input._,",
    "  },",
    "}",
  ],
};

export function defineEnums(definitions: DefinitionMap) {
  for (const name in FLAT_ENUMS) {
    definitions[name] = [
      "---@enum " + name,
      name + " = {",
      ...FLAT_ENUMS[name].map((value_name) => `  ${value_name} = {},`),
      "}",
    ];
  }

  for (const name in SPECIAL_ENUMS) {
    definitions[name] = SPECIAL_ENUMS[name];
  }
}
